name: Default Public Repository Ruleset
target: 
  - branch: main
enforcement: active

rules:
  - type: require_pull_request
    parameters:
      require_review: true
      required_approvals: 0
      require_code_owner_review: true
      require_conversation_resolution: true

  - type: require_status_checks
    parameters:
      required_checks:
        - build
        - test

  - type: restrict_force_pushes
    parameters:
      enabled: true

  - type: restrict_deletions
    parameters:
      enabled: true

  - type: require_signed_commits
    parameters:
      enabled: true

  - type: require_linear_history
    parameters:
      enabled: true